### ISSUE TITLE
Função Global - plataforma que permita aprendizado sobre finanças e contato entre usuários que buscam serviços relacionados e outros que oferecem esses serviços;

### ISSUE THREAD

**Issue by FelipeFaggion** [ribeirojose/EduFin#12]

**Comment by ribeirojose** [comment]
Talvez uma formulação melhor seja "permitir aprendizado sobre finanças e combinar demanda e oferta no mercado de serviços financeiros", qq vcs acham?

**Comment by FelipeFaggion** [comment]
Pode ser


Em 8 de abril de 2018 22:09, ribeirojose <notifications@github.com>
escreveu:
